// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbMCYkw7WkWBSAFF3hDQIJ-7vlveFSMow',
    appId: '1:786420067581:web:0ac99268344fa636f46294',
    messagingSenderId: '786420067581',
    projectId: 'millys-e2eb1',
    authDomain: 'millys-e2eb1.firebaseapp.com',
    storageBucket: 'millys-e2eb1.firebasestorage.app',
    measurementId: 'G-KYNMS4KV7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYXzMWDY-TitKoDch9T2r15f-fR0ojXM',
    appId: '1:786420067581:android:30bcc726b356da43f46294',
    messagingSenderId: '786420067581',
    projectId: 'millys-e2eb1',
    storageBucket: 'millys-e2eb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8AYE37VujI3Aiv0n-KYE7ns81LpnwxPA',
    appId: '1:786420067581:ios:22203552fd38e3cbf46294',
    messagingSenderId: '786420067581',
    projectId: 'millys-e2eb1',
    storageBucket: 'millys-e2eb1.firebasestorage.app',
    iosBundleId: 'com.millysshop.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8AYE37VujI3Aiv0n-KYE7ns81LpnwxPA',
    appId: '1:786420067581:ios:22203552fd38e3cbf46294',
    messagingSenderId: '786420067581',
    projectId: 'millys-e2eb1',
    storageBucket: 'millys-e2eb1.firebasestorage.app',
    iosBundleId: 'com.millysshop.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbMCYkw7WkWBSAFF3hDQIJ-7vlveFSMow',
    appId: '1:786420067581:web:b63025458b97b98ef46294',
    messagingSenderId: '786420067581',
    projectId: 'millys-e2eb1',
    authDomain: 'millys-e2eb1.firebaseapp.com',
    storageBucket: 'millys-e2eb1.firebasestorage.app',
    measurementId: 'G-GP0NQ9Z5Q3',
  );
}
